# Generated by Django 4.1.2 on 2022-10-31 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elderly', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elderly',
        ),
    ]
